name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 🚀 Features
    labels:
      - feature

  - title: 🐛 Bug Fixes
    labels:
      - bug

  - title: ⚡ Enhancements
    labels:
      - enhancement

change-template: '- $TITLE by @$AUTHOR (#$NUMBER)'

template: |
  ## What's Changed

  $CHANGES
